sudo: required

branches:
  except:
  - master

services:
- docker

before_install:
- docker pull ymian/golang:alpine-gcc

script:
- docker run -v $(pwd):/go/src/github.com/wise2c-devops/pagoda ymian/golang:alpine-gcc go build
- docker build -t wise2c/pagoda:$TRAVIS_BRANCH

deploy:
  provider: script
  script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push wise2c/pagoda:$TRAVIS_BRANCH
