sudo: required

services:
- docker

script:
- docker run -v $(pwd):/go/src/github.com/wise2c-devops/pagoda -w /go/src/github.com/wise2c-devops/pagoda ymian/golang:alpine-gcc go build
- docker build -t wise2c/pagoda:$TRAVIS_BRANCH .

deploy:
  script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push wise2c/pagoda:$TRAVIS_BRANCH
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$"