version: '2'
services:
  deploy:
    image: registry.cn-hangzhou.aliyuncs.com/wise2c-dev/wise-deploy:v0.3
    restart: always
    ports: 
    - 88:80
    - 8088:8080
    volumes:
    - /root/.ssh:/root/.ssh 
    - $PWD/wise2c-playbook:/workspace 
    - $PWD/deploy:/deploy
  ui:
    image: registry.cn-hangzhou.aliyuncs.com/wise2c-dev/deploy-ui:v0.2
    restart: always
    network_mode: "service:deploy"